### ISSUE TITLE
Java.Lang.IllegalArgumentException: the name must not be empty on Samsung Android Phone

### ISSUE THREAD

**Issue by angoudjou** [jfversluis/Plugin.Maui.CalendarStore#47] opened 2023-11-08 23:37 UTC
I implemented  me method to add event in a  Calendar, It works perfectly with other phone except Samsung Android Phone, I teste on 2  Samsung Android phones. and I got the same error  message. Notie it works with other Android phones.
Thank you for your helps
here is the full error message;

Java.Lang.IllegalArgumentException: the name must not be empty: null
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualObjectMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20416
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 894
   at Android.Content.ContentResolver.Insert(Uri url, ContentValues values) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Content.ContentResolver.cs:line 979
   at Plugin.Maui.CalendarStore.CalendarStoreImplementation.CreateEvent(String calendarId, String title, String description, String location, DateTimeOffset startDateTime, DateTimeOffset endDateTime, Boolean isAllDay)
   at MauiContributionLibrary.ViewModel.VmEventPage.AddToCalendar() in C:\Users\ngoudjou\source\repos\CalendarCode\MauiContributionLibrary\ViewModel\VmEventPage.cs:line 423
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: the name must not be empty: null
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
	at android.content.ContentResolver.insert(ContentResolver.java:2200)
	at android.content.ContentResolver.insert(ContentResolver.java:2162)
	at androidx.appcompat.app.AlertDialog_IDialogInterfaceOnClickListenerImplementor.n_onClick(Native Method)
	at androidx.appcompat.app.AlertDialog_IDialogInterfaceOnClickListenerImplementor.onClick(AlertDialog_IDialogInterfaceOnClickListenerImplementor.java:31)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: the name must not be empty: null
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:557)
	at android.content.ContentResolver.insert(ContentResolver.java:2200)
	at android.content.ContentResolver.insert(ContentResolver.java:2162)
	at androidx.appcompat.app.AlertDialog_IDialogInterfaceOnClickListenerImplementor.n_onClick(Native Method)
	at androidx.appcompat.app.AlertDialog_IDialogInterfaceOnClickListenerImplementor.onClick(AlertDialog_IDialogInterfaceOnClickListenerImplementor.java:31)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by jfversluis** [comment] 2023-11-09 08:40
Duplicate of #39

**Closed as not planned by jfversluis** 2023-11-09 08:40 UTC
